# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - janus-rabbitmq-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use

jobs:
  build-deploy:
       
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
     
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'janus-rabbitmq-test'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AFF752B810F04DFB81C6318149FB9344 }}
      - uses: azure/appservice-settings@v1
        with:
          app-name: 'janus-rabbitmq-test'
          mask-inputs: false
          slot-name: 'production'  # Optional and needed only if the settings have to be configured on the specific deployment slot
          general-settings-json: '[{ "alphavantage": "secrets.ALPHAVANTAGE", "value": "1", "slotSetting": false },{"cloudamqpconnectionstring": "secrets.CLOUDAMQPCONNECTIONSTRING", "value": "1", "slotSetting": false}]'
          id: settings
          alphavantage: ${{ secrets.ALPHAVANTAGE }}
          cloudamqpconnectionstring: ${{ secrets.CLOUDAMQPCONNECTIONSTRING }}         
