# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Timer Function - Get Stock Prices

on:
  push:
    paths:
      - GetStockPrices
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/GetStockPrices' # set this to the path to your web app project, defaults to the repository root
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/GetStockPrices/build-artifacts'
  TEST_PATH: '${{ github.workspace }}/AP.FunctionTests'
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use

jobs:
  build:
    name: Build ⛏️
       
    runs-on: ubuntu-latest
    env: 
      CloudAMQPConnectionString: ${{ secrets.CLOUDAMQPCONNECTIONSTRING }}
      AlphaVantage: ${{ secrets.ALPHAVANTAGE }}
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Environment'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
            

      - name: 'Restore dependencies'
        run: dotnet restore --packages .nuget

      - name: 'Test'
        run: dotnet test --verbosity normal  
        

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ${{ env.BUILD_OUTPUT_PATH }}
          popd
          
      # Upload the code artifact, this will be used later
      - name: 'Package Azure Function release build'
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
          retention-days: 5
          if-no-files-found: error
          
  deploy:
    name: Deploy 🚀
    
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      # Fetch published code
      - name: 'Download Azure function release build'
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
     
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'janus-rabbitmq-test'
          slot-name: 'Production'
          package: '${{ env.BUILD_OUTPUT_PATH }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AFF752B810F04DFB81C6318149FB9344 }}
