name: WEBAPI CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'AP.API/**'
      
env:
  API_PACKAGE_PATH: '${{ github.workspace }}/AP.API'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/AP.API/build-artifacts'
  DOTNET_VERSION: '6.0.x'

jobs:
  remove-old-artifacts:
    name: Remove Old Artifacts

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '14 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        skip-recent: 5

  build:
    name: Build ⛏️

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ env.BUILD_OUTPUT_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.BUILD_OUTPUT_PATH }}

  deploy:
    name: Deploy 🚀

    runs-on: ubuntu-latest
    
    needs: build
    
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AfgangsProjekt-API'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_73FBC5B292A54D6BAC7ABEFDF0A17179 }}
          package: .
